version: "3.9"
services:
  jupyter:
    image: jupyter/minimal-notebook:ubuntu-18.04
    container_name: my_jupyter_from_compose
    networks:
      - my_network_from_compose
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
  api:
    image: datascientest/fastapi:1.0.0
    container_name: my_api_from_compose
    networks:
      - my_network_from_compose
    ports:
      - "8000:8000"
  authentication:
    image: authentication:latest
    container_name: my_authentication_from_compose
    networks:
      - my_network_from_compose
    volumes:
      - .:/my_server
networks:
  my_network_from_compose:
