services:
  # jupyter:
  #   image: jupyter/minimal-notebook:ubuntu-18.04
  #   container_name: my_jupyter_from_compose
  #   networks:
  #     - my_network_from_compose
  #   volumes:
  #     - .:/home/jovyan/work
  #   ports:
  #     - "8888:8888"
  api:
    image: datascientest/fastapi:1.0.0
    container_name: my_api_from_compose
    networks:
      - my_network_from_compose
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import requests; requests.get(\"http://localhost:8000/status\").raise_for_status()'"]
      interval: 2m30s
      timeout: 3s
      start_period: 2s
      retries: 5
  authentication:
    image: authentication:latest
    container_name: my_authentication_from_compose
    networks:
      - my_network_from_compose
    volumes:
      - ./authentication:/my_server/code
      - ./log:/my_server/log
    depends_on:
      api:
        condition: service_healthy
    environment:
      LOG: 1
  authorization:
    image: authorization:latest
    container_name: my_authorization_from_compose
    networks:
      - my_network_from_compose
    volumes:
      - ./authorization:/my_server/code
      - ./log:/my_server/log
    depends_on:
      api:
        condition: service_healthy
    environment:
      LOG: 1
  content:
    image: content:latest
    container_name: my_content_from_compose
    networks:
      - my_network_from_compose
    volumes:
      - ./content:/my_server/code
      - ./log:/my_server/log
    depends_on:
      api:
        condition: service_healthy
    environment:
      LOG: 1
networks:
  my_network_from_compose:
